CREATE TABLE messages (
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
text VARCHAR NOT NULL
);

-- CREATE TABLE IF NOT EXISTS messages2 (
--     id       VARCHAR(60)  PRIMARY KEY,
--     text     VARCHAR      NOT NULL
--     );